name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.zig"
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - "**.zig"
      - ".github/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 6
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig: [0.13.0]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig }}
      - name: Run
        run: |
          zig fmt --check src/
          zig build
